name: mgit
base: core22
version: '0.0.1'
summary: MultiGit - Effortless Git Repositories Management Tool
description: |
  MultiGit is a simple CLI tool designed to streamline and automate 
  batch processing of commands across multiple Git repositories. 
  Ideal for developers and teams managing multiple repositories, 
  MultiGit provides an intuitive way to handle various Git actions, 
  saving you time and reducing repetitive tasks.
adopt-info: mgit

confinement: strict

architectures:
  - build-on: amd64

apps:
  mgit:
    command: bin/mgit
    plugs:
      - home
      - network

parts:
  mgit:
    plugin: go
    source: .
    source-type: git
    build-snaps: [go/latest/stable]
    override-build: |
      snapcraftctl build
      mv "$SNAPCRAFT_PART_INSTALL/bin/MultiGit" "$SNAPCRAFT_PART_INSTALL/bin/mgit"

