name: Build and Publish Snap for Multiple Architectures

on:
  push:
    tags:
      - "v*.*.*"
  workflow_dispatch:

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        arch: [ amd64, arm64 ]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up QEMU
        run: sudo apt-get install -y qemu-user-static # Enables multi-arch builds

      - name: Set up Snapcraft
        run: |
          sudo snap install snapcraft --classic
          sudo snap install multipass --classic

      - name: Build Snap
        env:
          SNAPCRAFT_BUILD_ENVIRONMENT: host
        run: |
          snapcraft clean
          snapcraft --destructive-mode --target-arch=${{ matrix.arch }}

      - uses: actions/upload-artifact@v4
        with:
          name: mgit-${{ matrix.arch }}
          path: mgit_*.snap

#      - name: Authenticate with Snap Store
#        env:
#          SNAPCRAFT_LOGIN_FILE: ${{ secrets.SNAPCRAFT_LOGIN_FILE }}
#        run: |
#          echo "$SNAPCRAFT_LOGIN_FILE" > snap_login_file
#          snapcraft login --with snap_login_file
#
#      - name: Publish Snap
#        run: snapcraft push *.snap --release=stable
