name: Build and Publish Snap for Multiple Architectures

on:
  push:
    tags:
      - "v*.*.*"
  workflow_dispatch:

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

#    strategy:
#      matrix:
#        arch: [ amd64, arm64, armhf ]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23.2'

      - name: Set up Snapcraft
        run: |
          sudo snap install snapcraft --classic
          sudo snap install multipass --classic

      - name: Build Snap
        id: build
        env:
          SNAPCRAFT_BUILD_ENVIRONMENT: host
        run: |
          snapcraft clean
          snapcraft --destructive-mode

      - name: Publish Snap
        uses: snapcore/action-publish@v1
        env:
          SNAPCRAFT_STORE_CREDENTIALS: ${{ secrets.SNAPCRAFT_STORE_LOGIN }}
        with:
          snap: ${{ steps.build.outputs.snap }}
          release: stable

#      - uses: actions/upload-artifact@v4
#        with:
#          name: mgit_amd64
#          path: mgit_*.snap



#      - name: Authenticate with Snap Store
#        env:
#          SNAPCRAFT_LOGIN_FILE: ${{ secrets.SNAPCRAFT_LOGIN_FILE }}
#        run: |
#          echo "$SNAPCRAFT_LOGIN_FILE" > snap_login_file
#          snapcraft login --with snap_login_file
#
#      - name: Publish Snap
#        run: snapcraft push *.snap --release=stable
