name: Build and Publish Snap for Multiple Architectures

on:
  push:
    tags:
      - "v*.*.*"
  workflow_dispatch:

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install QEMU
        run: sudo snap install qemu-virgil  # Enables multi-arch builds

      - name: Build Snap
        uses: snapcore/action-build@v1
        id: snapcraft

      - uses: actions/upload-artifact@v4
        with:
          name: snap
          path: ${{ steps.snapcraft.outputs.snap }}

#      - name: Authenticate with Snap Store
#        env:
#          SNAPCRAFT_LOGIN_FILE: ${{ secrets.SNAPCRAFT_LOGIN_FILE }}
#        run: |
#          echo "$SNAPCRAFT_LOGIN_FILE" > snap_login_file
#          snapcraft login --with snap_login_file
#
#      - name: Publish Snap
#        run: snapcraft push *.snap --release=stable
